### ISSUE TITLE
freezing on nuxt build

### ISSUE THREAD

**Issue by mixtale** [caub/mongo-lazy-connect#1]
thanks for your great job.
I'm using mongo-connect-sync on nuxt.js with SSR.
It's ok when I run my script in dev mode but if I run "nuxt build" command,
it will freeze build process because of this one line.

const db = connectSync('mongodb://localhost:27017/mycol');

so when I delete it, then build works ok without any freezing.

can you check this one?

**Comment by caub** [comment]
Hey @mixtale, can you provide some code so I can test and reproduce the issue? I haven't used this module in my apps yet. It should be working (except one case, of using `.find` directly after, you need to use await `.connect`, because `.find` itself returns a Stream not a Promise, so I can't chain it from the connection promise)


```js
const db = connectSync('mongodb://localhost:27017/mycol');
(async() => {
  await db.connect();
  const cols = await db.foo.find({ test: 2 }).limit(10).toArray(); // this will work
})()
```

**Comment by mixtale** [comment]
@caub thanks for your reply. I used it like below.

const connectSync = require('mongo-connect-sync');
const db = connectSync('mongodb://localhost:27017/mycol');

router.post('/api/foo', function(req, res){
  db.bar.find({ test: 2 }).limit(10).toArray();
})

as you can see, I don't query to mongodb during build works becuase all of db-works are under request call. so I can't use any async~await or promise in here.

**Comment by caub** [comment]
You can't make a real synchonous call, my library is just synchronous for the connect/open step, but each query (.findOne, .find, .update, ...) is async (I think only redis allows to do queries sync, but really that's not a good idea generally)

I just added .find()...toArray() in version 1.2.0

also update `db.bar.find` to `db.collection('bar').find` so your code should look like:

```js
const db = require('mongo-connect-sync')('mongodb://localhost:27017/mycol');

router.post('/api/foo', (req, res) => {
  db.collection('bar').find({ test: 2 }).limit(10).toArray()
    .then(docs => res.json(docs))
})
```

so even with SSR, you'll need to use promises, you can add some `loadData` methods in the routes definitions, and avoid using DB queries directly in routers anyway

**Comment by caub** [comment]
`mongo-connect-sync` and not `mongo-sync` as you thought maybe?

I'll close for now, and reopen if you still have an issue?
